kind: pipeline
type: docker
name: default

steps:
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host: 10.101.0.100
      username: wizznetadmin
      password:
        from_secret: wizznetadmin_password
      port: 22
      script:
        - echo hello
        - echo world
