kind: pipeline
type: docker
name: default

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 10.101.0.100
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - echo hello
        - echo world
